#!/bin/bash

THIS_DIR=$(realpath "$(dirname ${BASH_SOURCE[0]})")

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

cd "$BASE_DIR"

if [[ -z "${MATBENCH_WORK_DIR:-}" ]]; then
    export MATBENCH_WORK_DIR=$THIS_DIR
fi

exec python -m matrix_benchmarking.main "$@"
